language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install coveralls

branches:
  only:
    - master

script: nosetests --with-coverage -v --cover-package=models

after_success: coveralls

cache: pip